language: ruby
rvm:
- 2.6

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

branches:
  only:
    - master

sudo: required

before_install:
  - nvm install node
  - ruby -v

install:
  - gem install bundle
  - bundle install --jobs 4 --retry 3
  - npm install -g https://github.com/firebase/firebase-tools.git

before_script:
  - bundle exec jekyll build

script:
  - firebase deploy --project="$FIREBASE_PROJECT" --token "$FIREBASE_API_TOKEN"